org: fssantana
service: rag-server

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 29
  stage: dev
  region: us-east-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
    environment:
      WEAVIATE_URL: 'WEAVIATE_URL' #colocar as chaves aqui
      WEAVIATE_API_KEY: 'WEAVIATE_API_KEY'
      OPENAI_API_KEY: 'OPENAI_API_KEY'

plugins:
  - serverless-offline
  - serverless-s3-sync

custom:
  serverless-offline:
    httpPort: 5000

  s3BucketName: ${self:service}-${self:provider.stage}-site-v4

  s3Sync:
    - bucketName: ${self:custom.s3BucketName}
      localDir: public

resources:
  Resources:
    StaticSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    StaticSiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticSiteBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3BucketName}/*

outputs:
  WebsiteURL:
    Value: !GetAtt StaticSiteBucket.WebsiteURL
    Export:
      Name: WebsiteURL
 